### ISSUE TITLE
Unit test TrainingSet

### ISSUE THREAD

**Issue by henrike-94** [henrike-94/Predicting_bike_rental_demand#19]
### Tasks

- [x] Upgrade PyCharm to Python 3.10
- [x] Upgrade system to Python 3.10
- [x] Check installation error
- [x] Check requirements for unittest
- [x] Check if packages need to be reinstalled in Python 3.10
- [x] import unittest into TrainingSet.py
- [x] Run unittest on TrainingSet.py
- [ ] Make a sketch from [Getting Started With Testing in Python](https://realpython.com/python-testing/)

**Comment by henrike-94** [comment]
### Tasks

- [ ] Install package unittest

**Comment by henrike-94** [comment]
### The unittest module

#### Installation

```
PS C:\Users\henri> pip install unittest
WARNING: Ignoring invalid distribution -illow (c:\users\henri\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\henri\appdata\local\programs\python\python39\lib\site-packages)
ERROR: Could not find a version that satisfies the requirement unittest (from versions: none)
ERROR: No matching distribution found for unittest
WARNING: Ignoring invalid distribution -illow (c:\users\henri\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\henri\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\henri\appdata\local\programs\python\python39\lib\site-packages)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\users\henri\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
PS C:\Users\henri>
```

**Comment by henrike-94** [comment]
### Upgrade to Python 3.10

![image](https://user-images.githubusercontent.com/53818858/144851623-572282be-cc95-4986-8947-4f84fb6195de.png)

**Comment by henrike-94** [comment]
### Retry installing unittest

PyCharm

![image](https://user-images.githubusercontent.com/53818858/144856731-419f254f-66e1-42e8-913c-4f5dc48c4bba.png)

PowerShell

![image](https://user-images.githubusercontent.com/53818858/144856950-66a5f69d-55c2-48af-a65b-704e65a2562a.png)

**Comment by henrike-94** [comment]
## Installation error

### ERROR: "Could not find a version that satisfies the requirement unittest (from versions: none)"
### ERROR: "No matching distribution found for unittest"

**Comment by henrike-94** [comment]
## Run test on TrainingSet.py

### Default method: [unittest.main()](https://docs.python.org/3/library/unittest.html#unittest.main)
![image](https://user-images.githubusercontent.com/53818858/144861128-c0bb9e0d-75bf-4344-b06c-57d6e798bd88.png)

**Comment by henrike-94** [comment]
### Re-installing scikit-learn and fastai


PowerShell
```
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects
```

**Comment by henrike-94** [comment]
### Support

[Support scikit-learn](https://scikit-learn.org/stable/support.html)

**Comment by henrike-94** [comment]
## Run unittest.main(verbosity=2) on TrainingSet

```
Ran 0 tests in 0.000s
OK
Process finished with exit code 0
```
