### ISSUE TITLE
Train Set

### ISSUE THREAD

**Issue by henrike-94** [henrike-94/Predicting_bike_rental_demand#23]
## To Do

- [x] Create training file
- [x] Make a list of parameters to be measured
- [x] Also save validation set into file
- [x] Read files and define variables
- [x] Set up object RandomForestRegressor( ) and its methods fit( ), and print_score( )
- [x] Set up an alternative for print_score
- [x] Fix value error
- [x] Fix output problem: Execute print statements in console/move them to their respective definitions?
- [x] Check: After which line does the execution begin to slow down?
- [x] Return parameters
- [x] Select presentation format for GitHub
- [x] Move all visualisation statements to console?
- [x] Sketch out how the functions work: RandomForestRegressor( ), fit( ), and print_score( )

**Comment by henrike-94** [comment]
## Document efficiency criteria

#### Runtime

[Modul time in Python nutzen](https://www.python-lernen.de/python-modul-time.htm)

#### Rechenleistung

**Comment by henrike-94** [comment]
## Calculate score

`AttributeError: module 'fastai' has no attribute 'print_score'`

It seems like print_score is outdated.

**Comment by henrike-94** [comment]
### Fix value error

Possible solutions

- Fix number labels
- [Fix Exception](https://fixexception.com/scikit-learn/y-true-and-y-pred-have-different-number-of-output-param0-param1/)

**Comment by henrike-94** [comment]
### Visualization

**Comment by henrike-94** [comment]
### Visualize X_train and Y_train

Plot needs to display multiple x columns

What might work:

- [pyplot](https://matplotlib.org/stable/tutorials/introductory/pyplot.html)

**Comment by henrike-94** [comment]
### Creare Dashboard

- Library: Dash
- [This is How I Create Dazzling Dashboards Purely in Python](https://towardsdatascience.com/plotly-dashboards-in-python-28a3bb83702c)

**Comment by henrike-94** [comment]
### Return parameters

**Comment by henrike-94** [comment]
### Try out code selections

```
# Train Random Forest Regressor on dataframe trainingFirstCycle
import os
import psutil
import math
import time
import matplotlib.pyplot
import pandas
import sklearn
import fastai
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error
from sklearn.tree import export_graphviz
import plotly.express
import feather
import unittest
# Get the sum of the system and user CPU time of the current process in nanoseconds
# Nanoseconds since the epoch, which is 1 January 1601, 00:00:00 for Windows
# At the beginning of the process
start = time.process_time_ns()
# Read feather formatted trainingFirstCycle and define as array X_train. This is the training set
X_train = pandas.read_feather(
    "C:/Users/henri/OneDrive/Dokumente/Berufseinstieg/Sprachtechnologie/Predicting_Bike_Rental_Demand/FirstCycle/trainingFirstCycle.feather")
# Define X_train.rent_count as dependent variable Y_train. This is the dependent variable of the training set, the column to be predicted.
Y_train = X_train.rent_count
# Visualize X_train and Y_train in a scatterplot
# Some examples
Season=X_train.plot.scatter(x="season", y="rent_count")
Windspeed=X_train.plot.scatter(x="windspeed", y="rent_count")
Humidity=X_train.plot.scatter(x="humidity", y="rent_count")
Temperature=X_train.plot.scatter(x="temp", y="rent_count")
# Read csv formatted evalidateFirstCycle and define as array X_validate. This is the name of the validation set.
X_validate = pandas.read_csv(
    "C:/Users/henri/OneDrive/Dokumente/Berufseinstieg/Sprachtechnologie/Predicting_Bike_Rental_Demand/FirstCycle/validateFirstCycle.csv")
# Read y_name_validation.csv and define as Y_validate. This is the dependent variable of the validation set, the column to be predicted.
Y_validate = pandas.read_csv(
    "C:/Users/henri/OneDrive/Dokumente/Berufseinstieg/Sprachtechnologie/Predicting_Bike_Rental_Demand/FirstCycle/y_name_validation.csv")
# Create sklearn.ensemble.RandomForestRegressor() object
RF1 = sklearn.ensemble.RandomForestRegressor()
# Run fit method on training set
RF1.fit(X_train, Y_train)
# Visualize RF1.fit using export_graphviz
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.export_graphviz.html
# Extract a single tree from the forest
estimator=RF1.estimators_[5]
RF1_sample=sklearn.tree.export_graphviz(estimator,
                                        out_file="C:/Users/henri/OneDrive/Dokumente/Berufseinstieg/Sprachtechnologie"
                                                 "/Predicting_Bike_Rental_Demand/FirstCycle/RF1.dot")
# Predict y variable in validation set.
y_pred=RF1.predict(X_validate)
# TODO Visualize prediction?
y_true=Y_validate.rent_count.to_numpy()
# Evaluate prediction using root mean squared log error
scoreRMSLE=math.sqrt(sklearn.metrics.mean_squared_log_error(y_true, y_pred))
# TODO Visualize score
# DataFrame.plot.scatter()
# matplotlib.scatter(x,y)
# Return further parameters
# Nanoseconds since the epoch
# At the end of the process
end = time.process_time_ns()
runtime = end-start
#Code runs fine up to this point.
```


  File "<input>", line 75
    end = time.process_time_ns()
    ^
SyntaxError: invalid syntax

**Comment by henrike-94** [comment]
### Measuring performance parameters in the console?
