### ISSUE TITLE
Projektseite

### ISSUE THREAD

**Issue by Henrike-Schwenn** [henrike-94/Predicting_bike_rental_demand#56]
## To Do

- [x] Research how to
- [x] Create web page
- [x] Link to repo
- [x] henrike-94/Predicting_bike_rental_demand#63
- [x] Portfolio Data Science
- [ ] Wie funktioniert GitHub Pages?
- [ ] henrike-94/Predicting_bike_rental_demand#66
- [ ] henrike-94/Predicting_bike_rental_demand#64
- [ ] henrike-94/henrike-94.github.io#1
- [ ] Update tags 
- [ ] Zusammenarbeit João?

**Comment by henrike-94** [comment]
## Readme Guidelines

- [How to Write a Good README File for Your GitHub Project](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/)
